crudexample/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show', views.show),
    path('overview', views.dash),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee" 

class Category(models.Model):
    cat_name = models.CharField(max_length=200)
    class Meta:
        db_table = "Category"

class Test(models.Model):
    test = models.CharField(max_length=200)
    class Meta:
        db_table = "Test"

class Dash_Cateogry(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=200)
    category_level = models.IntegerField()
    business_profile_id = models.IntegerField()
    class Meta:
        db_table = "dash_category"

employee/forms.py
from django import forms
from employee.models import Employee, Category, Dash_Cateogry
from .widgets import BootstrapDateTimePickerInput


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Dash_Cateogry
        fields = ['category_name', 'category_id', 'category_level']


class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=BootstrapDateTimePickerInput()
    )

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from employee.forms import EmployeeForm, CategoryForm
from employee.models import Employee, Category, Dash_Cateogry
import datetime

# Create your views here.


# def emp(request):
#     if request.method == "POST":
#         form = EmployeeForm(request.POST)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect('/show')
#             except:
#                 pass
#     else:
#         form = EmployeeForm()
#     return render(request, 'index.html', {'form': form})


# def show(request):
#     employees = Employee.objects.all()
#     return render(request, "show.html", {'employees': employees})


# def edit(request, id):
#     employee = Employee.objects.get(id=id)
#     return render(request, 'edit.html', {'employee': employee})


# def update(request, id):
#     employee = Employee.objects.get(id=id)
#     form = EmployeeForm(request.POST, instance=employee)
#     if form.is_valid():
#         form.save()
#         return redirect("/show")
#     return render(request, 'edit.html', {'employee': employee})


# def destroy(request, id):
#     employee = Employee.objects.get(id=id)
#     employee.delete()
#     return redirect("/show")


# Category Function
def emp(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = CategoryForm()
    print(form)
    return render(request, 'index.html', {'form': form})


def show(request):
    cats_1 = Dash_Cateogry.objects.filter(
        category_level=0,
        business_profile_id=1
    )
    cats_2 = Dash_Cateogry.objects.filter(
        category_level=1,
        business_profile_id=1
    )
    cats_3 = Dash_Cateogry.objects.filter(
        category_level=2,
        business_profile_id=1
    )
    form = CategoryForm()
    return render(request, "show.html", {
        'cats_1': cats_1,
        'cats_2': cats_2,
        'cats_3': cats_3,
        'form': form
    })

def dash(request):
    
    from_date = datetime.datetime.now() - datetime.timedelta(days=30)
    to_date = datetime.datetime.now()
    return render(request, "overview.html", {
        'from_date': from_date,
        'to_date': to_date
    })


def edit(request, id):
    cats = Dash_Cateogry.objects.get(category_id=id)
    return render(request, 'edit.html', {'cats': cats})


def update(request, id):
    cats = Dash_Cateogry.objects.get(category_id=id)
    form = CategoryForm(request.POST, instance=cats)
    print (form)
    if form.is_valid():
        form.save()
        return redirect("/show")
    print(form.errors)
    return render(request, 'edit.html', {'cats': cats})


# def update(request, id):
#     cats = get_object_or_404(cats, category_id=id)
#     if request.POST:
#         form = CategoryForm(instance=cats, data=request.POST)
#     if form.is_valid():
#         form.save()
#         return HttpResponseRedirect('/show')
#     else:
#         form = CategoryForm(instance=cats)
#     print(form.errors)
#     return render_to_response('edit.html', {'cats': cats})


def destroy(request, id):
    cats = Dash_Cateogry.objects.get(category_id=id)
    cats.delete()
    return redirect("/show")

employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{cats.category_id}}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Category Name:</label>
          <div class="col-sm-4">
            <input 
              type="text"
              name="category_name"
              id="id_category_name"
              required
              maxlength="100"
              value="{{ cats.category_name }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Category Level:</label>
          <div class="col-sm-4">
            <input 
              type="text"
              name="category_level"
              id="id_category_level"
              required
              maxlength="100"
              value="{{ cats.category_level }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Business Profile:</label>
          <div class="col-sm-4">
            <input 
              type="text"
              name="business_profile_id"
              id="id_business_profile_id"
              required
              maxlength="100"
              value="{{ cats.business_profile_id }}"
            />
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

employee/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <form method="POST" class="post-form" action="/emp">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Enter Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Category Level:</label>
          <div class="col-sm-4">{{ form.category_level }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Category Name:</label>
          <div class="col-sm-4">{{ form.category_name }}</div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="sidenav">
      <a href=""
        ><img
          style="margin-bottom: 25px"
          src="{% static 'img/logo_default_white.png' %}"
          width="150px"
          alt=""
      /></a>
      <a href="overview">Overview</a>
      <a href="#">Fullfilment Master</a>
      <a href="#">Sales Order</a>
      <a href="#">Vendor Channels</a>
      <a href="#">Suppliers</a>
      <a href="#">Sales Channel</a>
      <a href="#">Inventory</a>
      <a href="#">Invoice</a>
      <a href="#">Products</a>
      <a href="#">Catalog</a>
      <a href="#">Retailer Invoices</a>
    </div>
    <div class="top-nav">
      <h4>Hello, Sean <span>S</span></h4>
    </div>

    <div style="margin-left: 250px; margin-top: 75px" class="main">
      <header>
        <h3>Manage Categories</h3>
      </header>
      <section id="cat">
        <div class="cat-1 cat">
          <h3>Category Level 01</h3>
          <form method="POST" class="post-form" action="/emp">
            {% csrf_token %}
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Name</label><br />
              <div
                style="display: inline-block; width: 87%"
                class="col-sm-4 form-control"
              >
                {{ form.category_name }}
              </div>
              <button
                style="display: inline-block"
                type="submit"
                class="btn btn-sm btn-primary"
              >
                Add
              </button>
            </div>
          </form>
          <table class="table-cat">
            <tbody>
              <tr>
                <th class="">#</th>
                <th class="">Category Name</th>
                <th class="">Action</th>
              </tr>
              {% for cat in cats_1 %}
              <tr>
                <td>{{ cat.category_id }}</td>
                <td>{{ cat.category_name }}</td>
                <td>
                  <a
                    class="btn btn-sm btn-info"
                    href="/edit/{{ cat.category_id }}"
                    ><span class="glyphicon glyphicon-pencil">Edit</span></a
                  >
                  <a
                    class="btn btn-sm btn-danger"
                    href="/delete/{{ cat.category_id }}"
                    >Delete</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="cat cat-2">
          <h3>Category Level 02</h3>
          <form method="POST" class="post-form" action="/emp">
            {% csrf_token %}
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Name</label><br />
              <div
                style="display: inline-block; width: 87%"
                class="col-sm-4 form-control"
              >
                {{ form.category_name }}
              </div>
              <button
                style="display: inline-block"
                type="submit"
                class="btn btn-sm btn-primary"
              >
                Add
              </button>
            </div>
          </form>
          <table class="table-cat">
            <tbody>
              <tr>
                <th class="">#</th>
                <th class="">Category Name</th>
                <th class="">Action</th>
              </tr>
              {% for cat in cats_2 %}
              <tr>
                <td>{{ cat.category_id }}</td>
                <td>{{ cat.category_name }}</td>
                <td>
                  <a
                    class="btn btn-sm btn-info"
                    href="/edit/{{ cat.category_id }}"
                    ><span class="glyphicon glyphicon-pencil">Edit</span></a
                  >
                  <a
                    class="btn btn-sm btn-danger"
                    href="/delete/{{ cat.category_id }}"
                    >Delete</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="cat cat-3">
          <h3>Category Level 03</h3>
          <form method="POST" class="post-form" action="/emp">
            {% csrf_token %}
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Name</label><br />
              <div
                style="display: inline-block; width: 87%"
                class="col-sm-4 form-control"
              >
                {{ form.category_name }}
              </div>
              <button
                style="display: inline-block"
                type="submit"
                class="btn btn-sm btn-primary"
              >
                Add
              </button>
            </div>
          </form>
          <table class="table-cat">
            <tbody>
              <tr>
                <th class="">#</th>
                <th class="">Category Name</th>
                <th class="">Action</th>
              </tr>
              {% for cat in cats_3 %}
              <tr>
                <td>{{ cat.category_id }}</td>
                <td>{{ cat.category_name }}</td>
                <td>
                  <a
                    class="btn btn-sm btn-info"
                    href="/edit/{{ cat.category_id }}"
                    ><span class="glyphicon glyphicon-pencil">Edit</span></a
                  >
                  <a
                    class="btn btn-sm btn-danger"
                    href="/delete/{{ cat.category_id }}"
                    >Delete</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </body>
</html>